name: Deploy FTP to staging
on: 
  workflow_dispatch:
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/staging'

    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: ðŸ•’ Generate timestamp to update version project
      run: echo "timestamp=$(date +%s)" >> $GITHUB_ENV

    - name: ðŸ”¨Creating .env file
      run: |
        echo "${{ secrets.FTP_STAGING_DEPLOY_ENV }}" | tr -d '\r' > ./src/.env
        echo -e "\nAPP_VERSION=${{ env.timestamp }}" >> ./src/.env

    - name: âœï¸ Write timestamp .htaccess file
      run: |
        echo -e "\n\n#Timestamp - ${{ env.timestamp }}" >> ./src/.htaccess
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_STAGING_HOST }}
        username: ${{ secrets.FTP_STAGING_USERNAME }}
        password: ${{ secrets.FTP_STAGING_PASSWORD }}
        local-dir: ./src/ 
        server-dir: ${{ secrets.FTP_STAGING_PROJECT_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          .env.example